var child = [
  { 'dupe': false, 'type': 4, 'name': 'components', 'dir': 'c0', 'linked': 0, 'url': 'http://localhost/phpmyadmin/templates/components/', 'fetched': true, 'code': 403, 'len': 316, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'database', 'dir': 'c1', 'linked': 0, 'url': 'http://localhost/phpmyadmin/templates/database/', 'fetched': true, 'code': 403, 'len': 314, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'error', 'dir': 'c2', 'linked': 0, 'url': 'http://localhost/phpmyadmin/templates/error/', 'fetched': true, 'code': 403, 'len': 311, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': false, 'type': 4, 'name': 'javascript', 'dir': 'c3', 'linked': 0, 'url': 'http://localhost/phpmyadmin/templates/javascript/', 'fetched': true, 'code': 403, 'len': 316, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xcf891cf6 },
  { 'dupe': false, 'type': 4, 'name': 'list', 'dir': 'c4', 'linked': 0, 'url': 'http://localhost/phpmyadmin/templates/list/', 'fetched': true, 'code': 403, 'len': 310, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xd6b0ad7a },
  { 'dupe': false, 'type': 4, 'name': 'navigation', 'dir': 'c5', 'linked': 0, 'url': 'http://localhost/phpmyadmin/templates/navigation/', 'fetched': true, 'code': 403, 'len': 316, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x6b5fd6a4 },
  { 'dupe': false, 'type': 4, 'name': 'table', 'dir': 'c6', 'linked': 0, 'url': 'http://localhost/phpmyadmin/templates/table/', 'fetched': true, 'code': 403, 'len': 311, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': true, 'child_cnt': 2, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0x631fc637 },
  { 'dupe': false, 'type': 4, 'name': 'test', 'dir': 'c7', 'linked': 0, 'url': 'http://localhost/phpmyadmin/templates/test/', 'fetched': true, 'code': 403, 'len': 310, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x8c6718d7 }
];
