var child = [
  { 'dupe': false, 'type': 32, 'name': 'developers.txt', 'dir': 'c0', 'linked': 2, 'url': 'http://localhost/phpmyadmin/doc/html/_sources/developers.txt', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'faq.txt', 'dir': 'c1', 'linked': 2, 'url': 'http://localhost/phpmyadmin/doc/html/_sources/faq.txt', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'import_export.txt', 'dir': 'c2', 'linked': 2, 'url': 'http://localhost/phpmyadmin/doc/html/_sources/import_export.txt', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'index.txt', 'dir': 'c3', 'linked': 2, 'url': 'http://localhost/phpmyadmin/doc/html/_sources/index.txt', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'other.txt', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost/phpmyadmin/doc/html/_sources/other.txt', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'privileges.txt', 'dir': 'c5', 'linked': 2, 'url': 'http://localhost/phpmyadmin/doc/html/_sources/privileges.txt', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'vendors.txt', 'dir': 'c6', 'linked': 2, 'url': 'http://localhost/phpmyadmin/doc/html/_sources/vendors.txt', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
