var child = [
  { 'dupe': false, 'type': 32, 'name': 'err_1.gif', 'dir': 'c0', 'linked': 2, 'url': 'http://localhost/uwc/images/err_1.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'err_2.gif', 'dir': 'c1', 'linked': 2, 'url': 'http://localhost/uwc/images/err_2.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'Error_Large.gif', 'dir': 'c2', 'linked': 2, 'url': 'http://localhost/uwc/images/Error_Large.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'grey_dot.gif', 'dir': 'c3', 'linked': 1, 'url': 'http://localhost/uwc/images/grey_dot.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'hr_1.gif', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost/uwc/images/hr_1.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'prof_1.gif', 'dir': 'c6', 'linked': 2, 'url': 'http://localhost/uwc/images/prof_1.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'pwr_2.gif', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost/uwc/images/pwr_2.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'red_dot.gif', 'dir': 'c8', 'linked': 1, 'url': 'http://localhost/uwc/images/red_dot.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'spacer.gif', 'dir': 'c9', 'linked': 2, 'url': 'http://localhost/uwc/images/spacer.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'stu_1.gif', 'dir': 'c10', 'linked': 2, 'url': 'http://localhost/uwc/images/stu_1.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'wcss_20.gif', 'dir': 'c11', 'linked': 2, 'url': 'http://localhost/uwc/images/wcss_20.gif', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
