var child = [
  { 'dupe': false, 'type': 4, 'name': 'bank', 'dir': 'c0', 'linked': 2, 'url': 'http://localhost/bank/', 'fetched': true, 'code': 200, 'len': 2965, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 13, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xf48d6e46 },
  { 'dupe': false, 'type': 4, 'name': 'etc', 'dir': 'c1', 'linked': 1, 'url': 'http://localhost/etc/', 'fetched': true, 'code': 404, 'len': 277, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'iso-8859-1', 'missing': true, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x1fa8001 },
  { 'dupe': false, 'type': 4, 'name': 'icons', 'dir': 'c2', 'linked': 2, 'url': 'http://localhost/icons/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'phpmyadmin', 'dir': 'c3', 'linked': 5, 'url': 'http://localhost/phpmyadmin/', 'fetched': true, 'code': 200, 'len': 10330, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 146, 'issue_cnt': [ 91, 0, 23, 32, 0 ], 'sig': 0x22f23b66 },
  { 'dupe': false, 'type': 4, 'name': 'uwc', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost/uwc/', 'fetched': true, 'code': 200, 'len': 1306, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 19, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x436f0b87 },
  { 'dupe': false, 'type': 4, 'name': 'var', 'dir': 'c5', 'linked': 1, 'url': 'http://localhost/var/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'webmail', 'dir': 'c6', 'linked': 2, 'url': 'http://localhost/webmail/', 'fetched': true, 'code': 200, 'len': 1176, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 4, 'issue_cnt': [ 7, 0, 0, 0, 0 ], 'sig': 0x4bea2f9a },
  { 'dupe': true, 'type': 32, 'name': '+li[i][\x27href\x27]+', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost/%2Bli[i][\x27href\x27]%2B', 'fetched': true, 'code': 404, 'len': 288, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'iso-8859-1', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': '+li[i][\x27off\x27].src+', 'dir': 'c9', 'linked': 2, 'url': 'http://localhost/%2Bli[i][\x27off\x27].src%2B', 'fetched': true, 'code': 404, 'len': 291, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'iso-8859-1', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': false, 'type': 32, 'name': 'auth', 'dir': 'c10', 'linked': 5, 'url': 'http://localhost/auth', 'fetched': true, 'code': 404, 'len': 277, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'iso-8859-1', 'missing': true, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x58f5346c }
];
